### ISSUE TITLE
Publish 2.5.3

### ISSUE THREAD

**Issue by cchantep** [playframework/anorm#144]
Publish a minor release 2.5.3 from the current master, including the Scala 2.12 artifact.

**Comment by cchantep** [comment]
@gmethvin It seems a tag 2.6.0-M1 has been added. Could you please clarify the release flow for standalone module such as Anorm (versioning was supposed to be independent)

**Comment by gmethvin** [comment]
Versioning is independent. And actually I don't think we needed a new release here. We were upgrading libraries for the Play 2.6.0-M1 release. This did have a dependency on the play-docs-sbt-plugin but there is no need to create a new release series for that since there are no incompatibilities introduced in the libraries themselves.

Sorry for creating unnecessary noise.

I am confused by the fact that there is a 2.5.x branch and a master branch, but you say the release should be done from the master branch. The 2.5.x branch doesn't seem to have been updated recently though. I'm not that familiar with this project, but I'm guessing 2.5.x just isn't being used?

Anyway, I'm fine with continuing the current versioning scheme you're using.

**Comment by cchantep** [comment]
Could a 2.5.3 be released? That's blocking some tickets (e.g. https://github.com/playframework/play-anorm/issues/10 )

**Comment by gmethvin** [comment]
@cchantep What do you want to do with the branches? Release 2.5.3 from master and kill the 2.5.x branch?

I don't work on this project much. What is the policy you've been using re backwards compatibility and release version?

**Comment by cchantep** [comment]
There has been not backport for Anorm for now. If required, a `2.4.x` could be created from the latest 2.4.x tag.

**Comment by gmethvin** [comment]
@cchantep There are already branches for [2.4.x](https://github.com/playframework/anorm/tree/2.4.x) and [2.5.x](https://github.com/playframework/anorm/tree/2.5.x). Do you mean that you never backport changes to those branches? Then I am also confused why we need a 2.5.x branch if 2.5.x releases are done from master.

So am I correct that we should release 2.5.3 from master and remove the 2.5.x branch?

**Comment by cchantep** [comment]
There has been no backport request.

> So am I correct that we should release 2.5.3 from master and remove the 2.5.x branch?

Yes

**Comment by cchantep** [comment]
The master version could be set to `2.5.4-SNAPSHOT` after release of 2.5.3 (will have a look at the setup of sbt release then)

**Comment by gmethvin** [comment]
Done https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/anorm_2.12/2.5.3/

**Comment by cchantep** [comment]
Thx
