### ISSUE TITLE
Support of ZonedDateTime with H2

### ISSUE THREAD

**Issue by mpapillon** [playframework/anorm#262]
### Anorm Version (2.5.x / etc)

2.6.5

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

macOS 10.15.2

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Zulu 8.42.0.21-CA-macosx) (build 1.8.0_232-b18)
OpenJDK 64-Bit Server VM (Zulu 8.42.0.21-CA-macosx) (build 25.232-b18, mixed mode)
```

### Library Dependencies

- Play: 2.8.0
- H2: 1.4.200

### Expected Behavior

1. Parse an H2 `TIMESTAMP WITH TIMEZONE` field to Java `ZonedDateTime`

### Actual Behavior

I got the following exception when I run a `SELECT` query:

```
anorm.AnormException: TypeDoesNotMatch(Cannot convert 2020-01-19 12:52:47.924+01: org.h2.api.TimestampWithTimeZone to Java8 ZonedDateTime for column ColumnName(user.login_date,Some(login_date)))
```

The table definition is:

```SQL
create table user
(
    id         identity primary key,
    username   varchar(32)             not null,
    login_date timestamp with timezone not null
)
```

And my query is:

```scala
def findLoginDate(userID: Long): Future[Option[ZonedDateTime]] =
  Future(db.withConnection { implicit connection =>
    SQL"""
         select login_date
         from user
         where id = $userID
       """.as(scalar[ZonedDateTime].singleOpt)
  })(ec)
```

**Comment by cchantep** [comment]
There is no plan for a H2 specific mapping module.

**Comment by wburgers** [comment]
So is there a way to override the default implicit conversions from test classes?

For example, I want to test "ServiceA" in test "TestServiceA".
ServiceA does the query.
In normal operation a Postgres database is used and everything works fine.
In a test, H2 is used and the AnormException is thrown.

I cannot just import an implicit converter into the ServiceA, because it makes use of the types defined in H2, of which the package is scoped to the tests.
E.G. "com.h2database" % "h2" % "1.4.200" % "test",
Is there any method to circumvent this and override the converter?
