### ISSUE TITLE
call-stack overflow on large datasets in WithResult.apply()

### ISSUE THREAD

**Issue by srushingiv** [playframework/anorm#53]
When using apply() to get a Stream of results on a large dataset, I ran into the situation in the topic.

I have posted a solution in StackOverflow here: http://stackoverflow.com/questions/13270825/is-there-an-easy-way-to-get-a-stream-as-output-of-a-rowparser/#31643766

But, this solution is obviously not ideal. Perhaps it'll provide clues on the direction you wish to take for this package.

I know that apply() is currently deprecated, but it would be very nice if you could use something akin to this approach to reinstate it.

**Comment by cchantep** [comment]
Hi,

As indicated in the [Streaming documentation](https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/ScalaAnorm.md#streaming-results), there are several ways to do it without the deprecated function.

The deprecation has been done because this function wasn't really streaming, and introduce some resource management issue. So I suggest you have a look at the other functions.

If you have other question, you can [ask on SO](http://stackoverflow.com/questions/tagged/anorm).

Best regards
