### ISSUE TITLE
Sonatype publication

### ISSUE THREAD

**Issue by cchantep** [playframework/anorm#620]
- Publish to `oss.sonatype.org` [doesn't work](https://github.com/playframework/anorm/actions/runs/11610449468/job/32329748149#step:7:548).
- Publish to `s01.oss.sonatype.org` is [denied](https://github.com/playframework/anorm/actions/runs/11612509786/job/32336151044#step:7:544)

> Updating `sonatypeRepository  := "https://s01.oss.sonatype.org/service/local"` in `project/Common.scala` doesn't work as expected (need to enforce in each module).

**Comment by mkurz** [comment]
This is caused by sbt...

So the error we get when publishing is:
```
2024-10-31 10:46:18.870Z  info [SonatypeService] sonatypeProfileName : org.playframework.anorm  - (SonatypeService.scala:28)
...
2024-10-31 10:46:26.742Z error [Sonatype] [MISSING_PROFILE(org.playframework.anorm,oss.sonatype.org)] Profile org.playframework.anorm is not found on oss.sonatype.org. In your sbt settings, check your sonatypeProfileName and sonatypeCredentialHost (try s01.oss.sonatype.org?)  - (Sonatype.scala:530)
```
However, we do set the correct `sonatypeProfileName`:
https://github.com/playframework/anorm/blob/56e45fa1398c866a378f31c5563fe8f03ecd9100/project/Common.scala#L22

Now, turns out something changed from sbt [1.9.6 to 1.9.7](https://github.com/sbt/sbt/compare/v1.9.6...v1.9.7):

```
$ sbt sonatypeProfileName
[info] welcome to sbt 1.9.6 (Eclipse Adoptium Java 17.0.13)
...
[info] anorm-pekko / sonatypeProfileName
[info]  org.playframework
[info] anorm-iteratee / sonatypeProfileName
[info]  org.playframework
[info] anorm-postgres / sonatypeProfileName
[info]  org.playframework
[info] anorm-tokenizer / sonatypeProfileName
[info]  org.playframework
[info] anorm-enumeratum / sonatypeProfileName
[info]  org.playframework
[info] anorm-akka / sonatypeProfileName
[info]  org.playframework
[info] anorm-core / sonatypeProfileName
[info]  org.playframework
[info] sonatypeProfileName
[info]  org.playframework
```

```
$ sbt sonatypeProfileName
[info] welcome to sbt 1.9.7 (Eclipse Adoptium Java 17.0.13)
...
[info] anorm-pekko / sonatypeProfileName
[info]  org.playframework.anorm
[info] anorm-iteratee / sonatypeProfileName
[info]  org.playframework.anorm
[info] anorm-postgres / sonatypeProfileName
[info]  org.playframework.anorm
[info] anorm-tokenizer / sonatypeProfileName
[info]  org.playframework.anorm
[info] anorm-enumeratum / sonatypeProfileName
[info]  org.playframework.anorm
[info] anorm-akka / sonatypeProfileName
[info]  org.playframework.anorm
[info] anorm-core / sonatypeProfileName
[info]  org.playframework.anorm
[info] sonatypeProfileName
[info]  org.playframework.anorm
```

Strange... Needs more investigation.

**Comment by mkurz** [comment]
So let's see where the `sonatypeProfileName` gets set...

In sbt 1.9.6:
```
sbt:anorm-parent> inspect sonatypeProfileName
[info] Setting: java.lang.String = org.playframework
[info] Description:
[info]  Profile name at Sonatype: e.g. org.xerial
...
[info] Defined at:
[info]  ./anorm/project/Common.scala:22
...
```
In sbt 1.9.7:
```
sbt:anorm-parent> inspect sonatypeProfileName
[info] Setting: java.lang.String = org.playframework.anorm
[info] Description:
[info]  Profile name at Sonatype: e.g. org.xerial
...
[info] Defined at:
[info]  (xerial.sbt.Sonatype.sonatypeSettings) Sonatype.scala:73
[info] Dependencies:
[info]  organization
...
```


So for 1.9.6 in the class `Common` and in 1.9.7 in `xerial.sbt.Sonatype.sonatypeSettings`.
So looking at the [sbt 1.9.6..1.9.7 diff](https://github.com/sbt/sbt/compare/v1.9.6...v1.9.7) its obvious this is caused by by this commit: https://github.com/sbt/sbt/commit/7beb23e818a181e2980da7261e6300d1d50e91da from 
- https://github.com/sbt/sbt/pull/7412 (1.9.x)
  - https://github.com/sbt/sbt/pull/7404 (1.10.x) 
- Fixes https://github.com/sbt/sbt/issues/1875 

I did some debugging (println :wink:) and can confirm in sbt 1.9.7 these two plugins always get loaded in this order:
```
...
xerial.sbt.Sonatype
...
Common
...
```
so of course Common always overrides the Sonatype plugins settings.
With the above fix for 1.9.7 however the order is always the other way round (looks like C comming before x).

Anyway, the real problem though is that our `Common` autoplugin does not depend on the `Sonatype` plugin - so that's why these two plugins have no deterministic order - which ones gets loaded first...

**Comment by mkurz** [comment]
Fix is easy:
- #621

**Comment by cchantep** [comment]
Still not ok for me, it publish tag as snapshot, not release: https://github.com/playframework/anorm/actions/runs/11683971119/job/32534263619#step:5:344

**Comment by mkurz** [comment]
Which tag? I can not see a new one here: https://github.com/playframework/anorm/tags

> https://github.com/playframework/anorm/actions/runs/11683971119/job/32534263619#step:5:344

You refer to a publish workflow that was triggered because of a pull request merge. There is no tag. This is totally expected and ok.

**Comment by mkurz** [comment]
Works:
- https://github.com/playframework/anorm/actions/runs/11689060884
- https://repo1.maven.org/maven2/org/playframework/anorm/anorm_2.13/2.8.0/
- https://repo1.maven.org/maven2/org/playframework/anorm/anorm_3/2.8.0/
