### ISSUE TITLE
sealed ResultSetParser 

### ISSUE THREAD

**Issue by pmonestie** [playframework/anorm#67]
Hi there,
When upgrading from play 2.3 to 2.4 I encountered some issue with my code that was using ResultSetParser.
In particular I had  a utility function
def vector[A](parser: RowParser[A]): ResultSetParser[Vector[A]] = {
      new ResultSetParser[Vector[A]] {...}

since I prefer Vector over List.

I Also I implemented a custom resultsetparser in order to read the returned id from SQL("...").executeUpdate   when doing, on mysql, an "insert into... on duplicate key update..."

I'm wondering now that ResultSetParser has gone private is there a way to provide a custom RSParser? 
Thanks for your help

**Comment by cchantep** [comment]
Hi, 

This type is not a general purpose one, but for internal use. If you need a similar one to be used outside of internal Anorm implementation.

Please use [StackOverflow](http://stackoverflow.com/questions/tagged/anorm) to ask question, rather than this tracker (which is for confirmed issue).

Best regards
